name: Build and Push Custom Matter Server

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-and-push-container-image:
    name: Build and Push Docker Image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4.2.2

      # Set up Python environment for building the package
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install build tools
        run: pip install build

      - name: Build Python package
        run: python -m build

      - name: Move Built Package to Docker Context
        run: cp dist/python_matter_server-*.tar.gz .

      # Set up Docker environment for building the image
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          tags: |
            ghcr.io/shaderhoth/python-matter-server:latest
          push: true
